// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZ_yIWQx6KFSvZhSqlnWrV5-MmNBzaFY',
    appId: '1:673399535159:web:06d3b29ca3ac4e7d00b1b2',
    messagingSenderId: '673399535159',
    projectId: 'flutter-hanyman',
    authDomain: 'flutter-hanyman.firebaseapp.com',
    storageBucket: 'flutter-hanyman.firebasestorage.app',
    measurementId: 'G-XGC29FJDYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJhFBTNvBy4vEbOpsKPMbdfeaS0bvAks',
    appId: '1:673399535159:android:41a5312ed1a9db7f00b1b2',
    messagingSenderId: '673399535159',
    projectId: 'flutter-hanyman',
    storageBucket: 'flutter-hanyman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjiK3MNC6CZ-TVwPDX5wgT5vxOW9VOO30',
    appId: '1:673399535159:ios:1db2e8dd0bac793300b1b2',
    messagingSenderId: '673399535159',
    projectId: 'flutter-hanyman',
    storageBucket: 'flutter-hanyman.firebasestorage.app',
    iosClientId: '673399535159-iield253gafsdogmlgldrodoj67eubs5.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.handyman.freelancer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjiK3MNC6CZ-TVwPDX5wgT5vxOW9VOO30',
    appId: '1:673399535159:ios:1db2e8dd0bac793300b1b2',
    messagingSenderId: '673399535159',
    projectId: 'flutter-hanyman',
    storageBucket: 'flutter-hanyman.firebasestorage.app',
    iosClientId: '673399535159-iield253gafsdogmlgldrodoj67eubs5.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.handyman.freelancer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZ_yIWQx6KFSvZhSqlnWrV5-MmNBzaFY',
    appId: '1:673399535159:web:7e3a940e6264648900b1b2',
    messagingSenderId: '673399535159',
    projectId: 'flutter-hanyman',
    authDomain: 'flutter-hanyman.firebaseapp.com',
    storageBucket: 'flutter-hanyman.firebasestorage.app',
    measurementId: 'G-KXRRVGGRGT',
  );
}
